// Run only against the isolated integration fixture.
import {createRequire} from 'node:module';
import fs from 'node:fs';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const output=process.env.PG_GYM_QA_OUTPUT||'/tmp/pg-gym-qa';fs.mkdirSync(output,{recursive:true});
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH,headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});
const context=await browser.newContext({viewport:{width:1440,height:1000}});
const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
const base=process.env.PG_GYM_E2E_URL||'http://localhost:18800';
const expect=(v,m)=>{if(!v)throw Error(m);};
try{
 await page.goto(base);await page.getByRole('button',{name:'Create an account',exact:true}).click();await page.getByLabel('Username').fill('browser-test');await page.getByLabel('Password',{exact:true}).fill('browser-testing-password');await page.getByRole('button',{name:'Create account',exact:true}).click();await page.waitForURL(base+'/');
 await page.getByRole('heading',{name:'Get started'}).waitFor();expect(await page.getByRole('heading',{name:'New benchmark'}).count()===0,'Workspace duplicates benchmark form');await page.screenshot({path:output+'/workspace-desktop.png',fullPage:true});
 await page.goto(base+'/settings?tab=environment');await page.getByRole('button',{name:'Show .env editor'}).click();await page.getByLabel('.env editor',{exact:true}).fill('MODEL_API_KEY=fixture-secret\nHF_TOKEN=hf-test-token');await page.getByRole('button',{name:'Save environment'}).click();await page.getByText('Environment saved. Values are hidden.').waitFor();expect(await page.getByLabel('Value 1',{exact:true}).inputValue()==='','Saved secret remained visible');await page.getByRole('button',{name:'Show .env editor'}).click();expect((await page.getByLabel('.env editor',{exact:true}).inputValue()).includes('fixture-secret'),'Reveal lost secret');await page.getByRole('button',{name:'Hide values'}).click();await page.screenshot({path:output+'/environment-desktop.png',fullPage:true});await page.getByRole('button',{name:'Connections',exact:true}).click();const form=page.locator('form').filter({has:page.locator('[name=base_url]')});await form.locator('[name=name]').fill('Test provider');await form.locator('[name=model]').fill('fixture-model');await form.locator('[name=base_url]').fill('http://127.0.0.1:18802/v1');await form.getByLabel('API key variable').selectOption('MODEL_API_KEY');await form.locator('[name=tools]').check();await form.getByRole('button',{name:'Add connection',exact:true}).click();await page.getByRole('button',{name:'Test',exact:true}).click();await page.getByText('Model is reachable and listed by the server').waitFor();
 await page.getByRole('button',{name:'Harness profiles',exact:true}).click();const profileForm=page.locator('form').filter({has:page.locator('[name=context_strategy]')});await profileForm.locator('[name=name]').fill('OpenCode profile');await profileForm.getByLabel('Harness',{exact:true}).selectOption('opencode');await profileForm.getByLabel('Markov context strategy').selectOption('truncate');await profileForm.getByRole('button',{name:'Add profile',exact:true}).click();await page.locator('.settings-row').filter({hasText:'OpenCode profile'}).getByRole('button',{name:'Edit',exact:true}).click();expect(await profileForm.getByLabel('Harness',{exact:true}).inputValue()==='opencode','Editing changed the harness');expect(await profileForm.getByLabel('Markov context strategy').inputValue()==='truncate','Editing changed the strategy');await profileForm.getByRole('button',{name:'Save profile',exact:true}).click();
 await page.goto(base+'/rl');await page.getByRole('button',{name:'Evaluate',exact:true}).click();expect(await page.getByLabel('Split',{exact:true}).inputValue()==='test','Evaluation defaulted to the train split');
 await page.goto(base+'/benchmark');await page.getByLabel('Suite',{exact:true}).selectOption('sql-function-set');await page.getByLabel('Task',{exact:true}).selectOption('area');await page.getByLabel('Model connection').selectOption({label:'Test provider · fixture-model'});await page.getByText('Configuration',{exact:true}).click();await page.locator('[name=max_turns]').fill('17');await page.waitForTimeout(5500);expect(await page.locator('[name=max_turns]').inputValue()==='17','Polling reset the form');await page.screenshot({path:output+'/benchmark-desktop.png',fullPage:true});
 expect(await page.locator('nav [aria-current=page]').count()===1,'Multiple active navigation items');const padding=await page.locator('.panel').first().evaluate(el=>parseFloat(getComputedStyle(el).paddingLeft));expect(padding>=18,'Missing panel padding');
 await page.getByRole('button',{name:'Run benchmark',exact:true}).click();await page.waitForURL(/\/jobs\//);const jobURL=page.url();await page.getByText('Waiting for a capable worker',{exact:true}).waitFor();await page.getByRole('button',{name:'Stop',exact:true}).click();await page.locator('.status-cancelled').waitFor();
 await page.goto(base+'/console?job='+new URL(jobURL).pathname.split('/').at(-1));await page.getByRole('heading',{name:'Execution console'}).waitFor();await page.getByLabel('Execution logs',{exact:true}).filter({hasText:'cancelled'}).waitFor();await page.getByLabel('Search logs').fill('no-such-event');await page.getByText('No events match your filters.').waitFor();await page.getByLabel('Search logs').fill('');await page.screenshot({path:output+'/console-desktop.png',fullPage:true});
 await page.goto(base+'/inference');await page.getByLabel('Connection',{exact:true}).selectOption({label:'Test provider · fixture-model'});await page.getByRole('button',{name:'Create conversation',exact:true}).click();await page.getByLabel('Message',{exact:true}).fill('Hello');await page.getByRole('button',{name:'Send',exact:true}).click();await page.getByText('Response from the test provider.',{exact:true}).waitFor({timeout:30000});await page.locator('.status-succeeded').waitFor();
 const chatURL=page.url();await page.reload();await page.getByText('Response from the test provider.',{exact:true}).waitFor();await page.getByLabel('Message',{exact:true}).fill('slow response');await page.getByRole('button',{name:'Send',exact:true}).click();await page.locator('.model-message').nth(1).getByText(/^Response/).waitFor({timeout:30000});await page.getByRole('button',{name:'Stop',exact:true}).click();await page.locator('.status-cancelled').waitFor({timeout:30000});await page.screenshot({path:output+'/inference-desktop.png',fullPage:true});
 for(const route of ['/','/benchmark','/results','/rl','/settings','/settings?tab=environment','/console',new URL(chatURL).pathname+new URL(chatURL).search,new URL(jobURL).pathname]){await page.setViewportSize({width:390,height:844});await page.goto(base+route);await page.waitForTimeout(1800);const b=await page.evaluate(()=>({w:innerWidth,s:document.documentElement.scrollWidth}));expect(b.s<=b.w+1,'Horizontal overflow '+route+': '+JSON.stringify(b));expect(await page.locator('h1').count()===1,'Missing title '+route);if(route==='/')await page.screenshot({path:output+'/workspace-mobile.png',fullPage:true});if(route==='/console')await page.screenshot({path:output+'/console-mobile.png',fullPage:true});if(route==='/benchmark')await page.screenshot({path:output+'/benchmark-mobile.png',fullPage:true});}
 await page.goto(base+'/settings');await page.getByRole('button',{name:'Account',exact:true}).click();await page.getByRole('button',{name:'Sign out',exact:true}).click();await page.waitForURL(base+'/login');expect(!errors.length,'Browser errors: '+errors.join('; '));console.log(JSON.stringify({ok:true,checks:['registration','profile edit preserves configuration','held-out evaluation defaults','connection form and provider check','benchmark submit/cancel','streamed chat','persistent chat','stop generation','panel padding','one active nav','nine mobile routes','workspace overview','environment save/hide/reveal','console search','logout']},null,2));
}catch(e){await page.screenshot({path:output+'/failure.png',fullPage:true});fs.writeFileSync(output+'/failure.html',await page.content());throw e;}finally{await browser.close();}
