FROM denoland/deno:2.9.6 AS build
WORKDIR /app
# Dependencies before the sources so edits do not refetch npm and jsr packages.
COPY web/deno.json web/deno.lock ./
RUN deno install --frozen --allow-scripts=npm:esbuild
COPY web/ ./
RUN deno task build
FROM denoland/deno:2.9.6
WORKDIR /app
COPY --from=build --chown=deno:deno /app /app
COPY --from=build --chown=deno:deno /deno-dir /deno-dir
USER deno
ENV DENO_NO_UPDATE_CHECK=1
EXPOSE 8000
CMD ["serve", "--allow-net", "--allow-env", "--allow-read=/app,/deno-dir", "--port=8000", "_fresh/server.js"]
